Scale for Action wrapper
BigThinkcode/AdaptiveCards pull request #126
Opened 2023-12-05 04:54 UTC by MohanSuri

# Related Issue

A Pull Request should close a **single** issue; multiple issues can be closed when the issues are **small and related**, but that should be an exception not the rule. Please keep Pull Requests small and targeted; large 'code drops' with dozens of files will be closed and asked to split into reviewable pieces. Reviews that need to be large due to dependencies will be
reviewed on a case-by-case basis.

Please use one of the well-known [github fixes keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to reference
the issue fixed with this PR (eg Fixes #<github issue number>). If an issue doesn't yet exist please create one to aid
in issue tracking.

**NOTE**: For multiple issues resolved by this PR use the corresponding keywords **every time** in a comma-delimited list per the reference
page above.

# Description

For all Pull Requests, please describe how the issue was fixed or how the feature was implemented from a summary level. This information will be used to help provide context to the reviewers of the pull request and should be additive to the issue being closed.

# Sample Card

If appropriate, please include a link to a card in one of the samples directories that can be used to validate this change. This can be an existing card or a card added with this PR.

# How Verified

How you verified the fix, including one or all of the following:
1. New unit tests that were added if any. If none were added please add a quick line explaining why not.
2. Existing relevant unit/regression tests that you ran
3. Manual scenario verification if any; ***Do include .gif's or screenshots of the testing you performed here if you think that it
will aid in code reviews or corresponding fixes on other platforms for eg.***

2023-12-05 18:57 UTC, sharshach requested changes

2023-12-05 18:57 UTC, sharshach commented on source/community/reactnative/src/adaptive-card.js
> +							scale={this.props.scale}
add the default value as 1

2023-12-05 18:57 UTC, sharshach commented on source/community/reactnative/src/adaptive-card.js
> +							scale={this.props.scale}
Also add the new prop in. AdaptiveCard.propTypes

2023-12-05 18:57 UTC, sharshach commented on source/community/reactnative/src/components/actions/action-wrapper.js
> +				paddingTop: this.props.scale * padding,
rename 

padding -> paddingTop if we are using only for this

2023-12-12 06:09 UTC, sharshach commented on source/community/reactnative/src/adaptive-card.js
> +							scale={this.props.scale ?? 1}
Add 1 to default Props and skip the "?? 1" here.

It would be a consistent design as per the entire file.

2023-12-12 08:29 UTC, sharshach approved these changes

2023-12-12 08:40 UTC, MohanSuri commented
@pragadeeshk please take a look at this PR

2023-12-18 04:58 UTC, pragadeeshk approved these changes
LGTM

2023-12-18 04:58 UTC, merged